// Generated by using torchexport::export() -> do not edit by hand
#include "torchvisionlib/exports.h"
#include <lantern/types.h>
void * p_torchvisionlib_last_error = NULL;

TORCHVISIONLIB_API void* torchvisionlib_last_error()
{
  return p_torchvisionlib_last_error;
}

TORCHVISIONLIB_API void torchvisionlib_last_error_clear()
{
  p_torchvisionlib_last_error = NULL;
}

torch::Tensor vision_ops_nms (torch::Tensor dets, torch::Tensor scores, double iou_threshold);
TORCHVISIONLIB_API void* _vision_ops_nms (void* dets, void* scores, double iou_threshold) {
  try {
    return  make_raw::Tensor(vision_ops_nms(from_raw::Tensor(dets), from_raw::Tensor(scores), iou_threshold));
  } TORCHVISIONLIB_HANDLE_EXCEPTION
  return (void*) NULL;
}
int test (void* path);
TORCHVISIONLIB_API int _test (void* path) {
  try {
    return  (test(path));
  } TORCHVISIONLIB_HANDLE_EXCEPTION
  return 10;
}
