# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_f <- function(path) {
    .Call('_torchvisionlib_test_f', PACKAGE = 'torchvisionlib', path)
}

